/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { TransactionUpdateManyWithoutAccountingPeriodsInput } from "./TransactionUpdateManyWithoutAccountingPeriodsInput";
import { AccountPeriodTypeWhereUniqueInput } from "../../accountPeriodType/base/AccountPeriodTypeWhereUniqueInput";
import { UserUpdateManyWithoutAccountingPeriodsInput } from "./UserUpdateManyWithoutAccountingPeriodsInput";
@InputType()
class AccountingPeriodUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  end?: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  start?: Date;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutAccountingPeriodsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutAccountingPeriodsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutAccountingPeriodsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutAccountingPeriodsInput;

  @ApiProperty({
    required: false,
    type: () => AccountPeriodTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountPeriodTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountPeriodTypeWhereUniqueInput, {
    nullable: true,
  })
  typeId?: AccountPeriodTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutAccountingPeriodsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutAccountingPeriodsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutAccountingPeriodsInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutAccountingPeriodsInput;
}
export { AccountingPeriodUpdateInput };
